### ISSUE TITLE
[Bug]: Newlines missing from set variable auto-generated functions

### ISSUE THREAD

**Issue by akulkar4** [microsoft/mu_feature_config#107]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

With the input xml example below, `SetupDataPkg/Tools/KnobService.py` generates the following output in the private header file. 

The setter function is missing a couple of new lines and isn't properly formatted.

Input XML:
```xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">
  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{5db63705-b75f-429b-a331-0fe95af09e19}">
    <!-- configuration knobs -->
    <Knob name="example" type="bool" help="Example help" />
    <!-- end configuration knobs -->
  </Knobs>
</ConfigSchema>
```

Output:
```C
#ifdef CONFIG_SET_VARIABLES
// Set the current value of the example knob
bool config_set_example(bool value) {    return set_knob_value(KNOB_example, &value);
}
#endif // CONFIG_SET_VARIABLES
```

### Expected Behavior

The generated setter output should look like something like this: 

```C
#ifdef CONFIG_SET_VARIABLES
// Set the current value of the example knob
bool config_set_example(bool value) {    
    return set_knob_value(KNOB_example, &value);
}
#endif // CONFIG_SET_VARIABLES
```

### Steps To Reproduce

Use the example xml above to auto-generate configuration knob header files using `SetupDataPkg/Tools/KnobService.py`. The setter-function in the private header file (`priv_hdr.h`) will be malformed.

```Bash
KnobService.py generateheader example.xml pub_hdr.h priv_hdr.h
```

### Build Environment

```markdown
- OS(s): Ubuntu 20.04
- Tool Chain(s): gcc-arm-10.2-2020.11
- Targets Impacted: RELEASE, DEBUG
```

### Version Information

```text
Commit: ae681b2
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by os-d** [comment]
Fixed in commit https://github.com/microsoft/mu_feature_config/commit/07eeb3c3f0c821de18fc7047877a4141c32cd466
