### ISSUE TITLE
[Feature]: Support Applying Config Binary to Uefi Vars On Linux

### ISSUE THREAD

**Issue by os-d** [microsoft/mu_feature_config#349]
### Feature Overview

Add support for applying config from Linux

### Solution Overview

Write a Linux specific script to accompany the Windows specific script.

### Urgency

Medium

### Are you going to implement the feature request?

I will implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by apop5** [comment]
I found this recent uefivar python package that might be able to help. 

https://pypi.org/project/uefivars/
