### ISSUE TITLE
[Feature]: Add the include concept into the XML file to increase the reusability

### ISSUE THREAD

**Issue by MarcChen46** [microsoft/mu_feature_config#352]
### Feature Overview

In current design, each project needs to create their own XML file as a default golden config, but from project point of view, it is possible that there are multiple config knobs are the same and common across different projects, if we could add the "include" concept in the XML, then it could increase the reusability of the common XML file.

### Solution Overview

- Add some reserved keyword like "!include" in XML
- The "!include" must have relative path or absolute path after it. ex "!include "../Template/Example.xml""
- Create a whole new temp XML file in the same folder that expend the content of the "!include "../Template/Example.xml""
- Use the new temp XML to proceed the original process including header file generation
- From ConfigEditor point of view it would also create a whole new temp XML to expand the !include file and load the new temp XML file.

### Urgency

Low

### Are you going to implement the feature request?

Someone else needs to implement the feature

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

@ray007330 would study how to implement it and update detail here later.

**Comment by os-d** [comment]
I believe we can solve the pain point you bring up in a different way that more closely aligns with the goals of mu_feature_config. One large goal of this configuration system is to enable platform owners to create meaningful configuration options that are distinct from the set of silicon/oem/core configuration options. Many platforms carry far too many configuration options that are not meaningful to the platform beyond an initial tuning point. To this end, I think we can enable the tuning case with autogenerated configuration knobs from silicon/oem/core configuration options that should provide a better experience than XML inclusion and then work to have the platform only use these options at a tuning time and trim down the platform options to meaningful user supplied configuration options by shipping time. To that end, I am closing this request, but opening another issue to track the autogen work.
