### ISSUE TITLE
[Feature]: Add function in config editor to read/write system variable in runtime

### ISSUE THREAD

**Issue by kanechen66** [microsoft/mu_feature_config#408]
### Feature Overview

Problem statement:
1. To read/write BIOS var during runtime, we need to use WriteConfVarListToUefiVars.py ReadUefiVarsToConfVarList.py, and configeditor altogether.
it sometimes creates confusion by testers because they are not sure whether the settings are really read from or written to the system.
2. There is not status box in the tool to tell what configeditor has done or what xml, vl file is loaded.

Proposal:
To gain efficiency and avoid confusion, it will be great if we can have a menu/button in config editor to read/write variable directly.
The status textbox in the bottom will be very helpful for users/testers to understand the current status of ConfigEditor

### Solution Overview

Here is the proposed solution. pls check the below picture
![Image](https://github.com/user-attachments/assets/38c10e1d-552c-4315-9291-91a632028f0e)

### Urgency

Low

### Are you going to implement the feature request?

I will implement the feature

### Do you need maintainer feedback?

Maintainer feedback requested

**Comment by apop5** [comment]
I think this would be fine.

A couple of pitfalls that have to be addressed as part of this design

- This needs to be tied to the current system. It needs some way to know that the XML loaded matches what is currently running on the system, and that the XML is not some older version, or some random xml file that was pulled from somewhere else.
- It will need to delete the variables as well, essentially resetting the system back to use the built in defaults and not use any nvram varaible from the xml.

@kuqin12 @os-d 

Any other items I am missing if this is going to be implemented?

**Comment by MarcChen46** [comment]
> I think this would be fine.
> 
> A couple of pitfalls that have to be addressed as part of this design
> 
> * This needs to be tied to the current system. It needs some way to know that the XML loaded matches what is currently running on the system, and that the XML is not some older version, or some random xml file that was pulled from somewhere else.
> * It will need to delete the variables as well, essentially resetting the system back to use the built in defaults and not use any nvram varaible from the xml.
> 
> [@kuqin12](https://github.com/kuqin12) [@os-d](https://github.com/os-d)
> 
> Any other items I am missing if this is going to be implemented?

The idea about delete variables for resetting the system back to default is a good suggestion.
For the XML compatible check, so far since there is no version or data info from BIOS image, so far I can only think about checking the variable size the same with sum of XML, unless we can add some more version info in the XML and save it in NVRAM, any other suggestion on the XML compatible check?

**Comment by kanechen66** [comment]
the PR is landed. so close this issue
